services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JsonSchema\Validator: ~
  Basilicom\JsonSchemaRequestValidator\Validator\JsonSchemaValidator: ~
  Basilicom\JsonSchemaRequestValidator\EventListener\JsonSchemaRequestValidatorListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController}