<?php

namespace Basilicom\JsonSchemaRequestValidator\Validator\JsonSchema\Exception;

use Basilicom\JsonSchemaRequestValidator\Exception\GeneralJsonSchemaRequestValidatorException;

class NoFilePathProvidedException extends GeneralJsonSchemaRequestValidatorException
{
}
